### ISSUE TITLE
BTC,LTC, and ETH will need to pair with major currencies other than the USD like, GBP, EUR, CAD, AUD, HKD, CNY

### ISSUE THREAD

**Issue by pringers** [pringers/usd.pw#2]

**Comment by JPeroutek** [comment]
This is possible. Just add the appropriate endpoint files and modify `config.py`

**Comment by pringers** [comment]
As for the altcoins, it'd be

`COIN/BTC * BTC/CURRENCY`

sick bruh

I'll add those in a bit, that'll be about 20-30 more pairings.

**Comment by JPeroutek** [comment]
Yeah, put all target currencies in the `TARGET_SYMBOLS` list and the alts in `SUPPORTED_SYMBOLS`
